[package]
name = "property_filter"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
health = { path = "../common/health" }
serve-metrics = { path = "../common/serve_metrics" }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
futures = { workspace = true }
time = { workspace = true }
serde = { workspace = true }
qp-trie = { workspace = true }
fxhash = { workspace = true }
sqlx = { workspace = true }
metrics = { workspace = true }
anyhow = { workspace = true }
tokio = { workspace = true }
axum = { workspace = true }
envconfig = { workspace = true }

[lints]
workspace = true
