# Generated by Django 4.2.18 on 2025-05-03 19:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posthog", "0721_eventingestionrestrictionconfig_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="secret_api_token",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="team",
            name="secret_api_token_backup",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
